### ISSUE TITLE
Create Milestones

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#59] opened 2012-06-28 23:04 UTC
**NEW: create a gui that manages the milestones and priorities. Rollback to 2008/2009 -version to keep things simple [6] with Ticgit -version. If content-hosts such as Github.com or Bitbucket.org do not want to suppot exportation of tickets, we cannot do much here -- stop developing with them, simple.**

**OLD:** Some clutter [1][2][3],  ticgit Bitbucket -style-clone-UI [4] and Github -style-graphical-bells-and-whistles-analysis-tool [5].

**References**
[1] https://github.com/jeffWelling/ticgit/issues/58#issuecomment-6642576
[2] https://github.com/jeffWelling/ticgit/issues/57
[3] https://github.com/jeffWelling/ticgit/issues/56
[4] https://github.com/jeffWelling/ticgit/issues/51
[5] http://stackoverflow.com/questions/11251941/how-can-i-see-github-style-things-such-as-punchcards-and-timeline-of-git-repo
[6] https://github.com/jeffWelling/ticgit/issues/64

**Comment by jeffWelling** [comment] 2012-07-01 18:25
The command line interface for the milestones and priorities (aka points) will be done first because that's what I use and that's what I'll be using to test part the final product before releasing the gem.

A request to rollback to the old version numbering system should be split out into it's own ticket.

If they already have an API, then I don't understand why we need them to allow exporting tickets, especially if said API allows write access.

**Comment by jeffWelling** [comment] 2012-08-13 10:42
Now that I've pushed out another release of TicGit-ng that has addressed a number of different bugs, I hope to be getting to writing the milestones portion of the code shortly, bear with me...

**Comment by jeffWelling** [comment] 2012-08-13 10:47
Duplicate: https://github.com/jeffWelling/ticgit/issues/59

Closed as duplicate of Issue 59.

**Closed as completed by jeffWelling** 2012-08-13 10:47 UTC
