### ISSUE TITLE
Can't list bugs in project

### ISSUE THREAD

**Issue by nikreiman** [jeffWelling/ticgit#78] opened 2012-10-25 07:58 UTC
When running `ti list`, I now get the following error:

```
/var/lib/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/command/list.rb:67:in `block in execute': undefined method `[]' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/command/list.rb:63:in `each'
    from /var/lib/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/command/list.rb:63:in `execute'
    from /var/lib/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/cli.rb:56:in `execute!'
    from /var/lib/gems/1.9.1/gems/TicGit-ng-1.0.2.17/lib/ticgit-ng/cli.rb:9:in `execute'
    from /var/lib/gems/1.9.1/gems/TicGit-ng-1.0.2.17/bin/ti:13:in `<top (required)>'
    from /usr/local/bin/ti:19:in `load'
    from /usr/local/bin/ti:19:in `<main>'
```

Everything worked fine in this repo up until yesterday; I think that things stopped working after a (successful) call to `ti sync`.

**Comment by jeffWelling** [comment] 2012-10-25 13:53
Thank you for bringing this bug to my attention. It seems as though a ticket may have been missing a ticket id, I will investigate this issue. I may need your assistance replicating this, I'll let you know.
Thanks,
Jeff

**Comment by jeffWelling** [comment] 2012-10-25 15:19
Hi Nik,
I wasn't able to reproduce your problem on my end so I might need your help. Are you able to push this repo to github temporarily so I could take a look at it?
Did you happen to do a Control+C in the middle of the sync operation?
From the error I'm getting the impression that ticket_id is null, which is why trying to do [] on it would fail, but why is that null is the question.

To try and reproduce this I did this;
1) Created a new git repo
2) Created a text file with a couple words in it
3) Added and Committed that file to git
4) `ti init`
5) Created a new ticket
6) Created a new comment on that ticket, for good measure
7) Created a new git repo
8) Created a remote pointing to the first git repo called 'origin' so that `ti sync` would work
9) `ti init` on the second repo
10) `ti sync`
11) `ti list`

I didn't get any errors, and it even printed the ticket from the first git repository. There must be something that we're both missing here...

**Comment by nikreiman** [comment] 2012-10-25 17:48
If you'd like to see the repo, it's at https://github.com/teragonaudio/MrsWatson

I haven't run `ty sync` since running into the problem. If you clone it and still can't reproduce, I can zip up my clone and send it to you for further testing. Would that be useful?

**Comment by jeffWelling** [comment] 2012-10-25 19:34
Hey Nik,

I just pulled down a copy of https://github.com/teragonaudio/MrsWatson and I was able to replicate that issue. I'm still investigating but since I'm able to replicate this issue I shouldn't need you to send me a zipped clone quite yet, if at all.

I'll take a look at this and get back to you when I have something note-worthy.

Thanks again.

**Comment by nikreiman** [comment] 2012-10-26 12:21
Cool, glad that it's easy to reproduce and not a "one off" type of bug. Let me know if you need anything else.

**Comment by jeffWelling** [comment] 2012-10-26 15:30
I think I've found why ticket_id is null. It doesn't exist lol.

I'm guessing these tickets were created by the old version of Ticgit?

For a control, I cloned a repository (ticgit in this example) and made a new ticket with ticgit. Then I edited the source to print the value returned by read_tickets, and I get this:  
http://pastebin.com/JKpSgx5D

And when I use the same source to `ti list` MrsWatson, I get this:  
pastebin.com/Y6RYjNLX

The good news is, it's fixable with relative ease. The bad news is, I wasn't aware of this problem before-hand and should look into writing a component that detects tickets which were written with the old version and does behind the scenes magic to make it work in the new version. The other good news, that component can be written in such a way that it's largely backwards compatible with the original Ticgit so that if you comment on a repo where another developer is using the old version he should still be able to see your ticket and the associated attributes.

More to come when I have time to get out my development stick after work and bang on this some more.

**Comment by jeffWelling** [comment] 2012-10-27 01:01
I'm stil investigating the issue but I needed to ask you a question:

After doing `sudo apt-get install ticgit` to get the old version, did you have to create the ticgit branch or did it automatically create it for you when you did `ti new` or `ti list` or something?

I'm doing some basic experiments, but when I do:
1) mkdir test_dir
2) git init
3) echo 'fubar fubar fubar' >> fubar.txt
4) git add fubar.txt
5) git commit -m "fubar"
6) ti new

But on the last step I get an error indicating the 'ticgit' branch is missing, which is odd because even the old versions of TicGit were supposed to create the branch for you.  Did you have to manually create the ticgit branch when using the old version of 'ticgit'.

**Comment by nikreiman** [comment] 2012-10-28 16:48
I'm actually using TicGit on two different computers, my Linux laptop at work and a Mac at home. They might have different versions installed, but I can check to make sure. Anyways, I ran ti init on my mac at home, but my office machine is the one which had the error. I had to checkout the remote branch, but then TicGit ran perfectly on it until I ran into this error.

-Nik

**Comment by jeffWelling** [comment] 2013-06-15 16:32
Hi Nick, sorry it's been so long but were you able to check the versions on the laptop at work vs the mac at home?

**Comment by nikreiman** [comment] 2013-06-17 12:23
Hi Jeff, sorry but I stopped using ticgit long ago, I can't reproduce this
issue for you any longer. =/

-Nik

**Closed as completed** 2013-06-18 02:18 UTC
Labels: Bug
